/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Accounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Activities": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Clients": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Deals": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "People": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Pipelines": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Sessions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Tags": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "VerificationTokens": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}